// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUnZLIe3glX9ubscsAhHmjG1TI1epJGYs',
    appId: '1:511179812666:web:ec55af3fbf15a8bbb36a03',
    messagingSenderId: '511179812666',
    projectId: 'gestionapppi',
    authDomain: 'gestionapppi.firebaseapp.com',
    storageBucket: 'gestionapppi.appspot.com',
    measurementId: 'G-9QGE6Y3PGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvLyv6ZULv1bCVmk7mWmoMMiNK3ivuJxs',
    appId: '1:511179812666:android:030fbc6edf7025ffb36a03',
    messagingSenderId: '511179812666',
    projectId: 'gestionapppi',
    storageBucket: 'gestionapppi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyYYfY5zQJfRfeJTagIl3Jd-0xH_WwKyA',
    appId: '1:511179812666:ios:4f6dc5e0511b7731b36a03',
    messagingSenderId: '511179812666',
    projectId: 'gestionapppi',
    storageBucket: 'gestionapppi.appspot.com',
    iosClientId: '511179812666-dcq3cb6rfjns7qgb54uriqdtks675jmv.apps.googleusercontent.com',
    iosBundleId: 'com.llyto.gestionApp',
  );
}
